name: manage-azure-policy-c69929be
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run test'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/网络安全等级保护（三级）_774cb09b4417441aaa539793/**'
#      - .github/workflows/manage-azure-policy-c69929be.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_c69929be}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/网络安全等级保护（三级）_774cb09b4417441aaa539793/**
